{% set name = "pynamodb-encoder" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 40d5b8b465ea51d3818eef7a8e085634b31b72edbb8cb6d9680e3c412945a2f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8
  run:
    - pynamodb >=6.0.0,<7.0.0
    - python >=3.8

test:
  imports:
    - pynamodb_encoder
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lyang/pynamodb-encoder
  summary: Helper classes that encode/decode pynamodb models to/from JSON serializable dict
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
